name: Example workflow for Python using Snyk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r pip-sample/requirements.txt

  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        # COMMAND: "pip3 install -r pip-sample/requirements.txt"
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: 
          --file=pip-sample/requirements.txt
          --package-manager=pip
