name: Example workflow for Python using Snyk
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - name: Build Python Project
      with:
        python-version: '3.9'
        architecture: 'x64'
    - run: pip install -r pip-sample/requirements.txt
    
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        # COMMAND: "pip3 install -r pip-sample/requirements.txt"
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: 
          --file=pip-sample/requirements.txt
          --package-manager=pip
